/**
 * Deterministic in-memory backend for the context contract.
 *
 * Implements exactly the query/traversal surface ContextBuilder consumes, with
 * simple, fully specified semantics and pseudo-random-but-fixed scores, so the
 * builder's own logic (seeding, re-ranking, expansion, budgets, rendering) is what
 * the recorded results characterize. Every call returns fresh result objects:
 * callers are allowed to mutate them.
 */
import type { Node, Edge, EdgeKind, NodeKind, SearchResult, Subgraph } from '../../src/types';
import type { QueryBuilder } from '../../src/db/queries';
import type { GraphTraverser } from '../../src/graph';

export interface FakeWorld {
  nodes: Node[];
  edges: Edge[];
  /** Reported by getDominantFile(); undefined models a project without one. */
  dominantFile?: { filePath: string; edgeCount: number; nextEdgeCount: number } | null;
  /** Paths the project declared peripheral. */
  deprioritized?: (filePath: string) => boolean;
  /** Paths flagged generated by their content header (in addition to naming conventions). */
  headerGenerated?: ReadonlySet<string>;
}

/** Stable 32-bit FNV-1a → [0, 1). */
export function unit(text: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash / 0x100000000;
}

/** Scores are quantized to halves so ties (and therefore stable ordering) occur. */
const quantize = (value: number): number => Math.round(value * 2) / 2;

interface Options { kinds?: NodeKind[]; limit?: number }

export function createFakeBackend(world: FakeWorld): { queries: QueryBuilder; traverser: GraphTraverser } {
  const byId = new Map(world.nodes.map((node) => [node.id, node]));
  const outgoing = new Map<string, Edge[]>();
  for (const edge of world.edges) {
    const list = outgoing.get(edge.source);
    if (list) list.push(edge);
    else outgoing.set(edge.source, [edge]);
  }
  const incoming = new Map<string, Edge[]>();
  for (const edge of world.edges) {
    const list = incoming.get(edge.target);
    if (list) list.push(edge);
    else incoming.set(edge.target, [edge]);
  }
  const kindOk = (node: Node, kinds?: NodeKind[]): boolean => !kinds || kinds.length === 0 || kinds.includes(node.kind);
  const ranked = (hits: SearchResult[], limit?: number): SearchResult[] => {
    const ordered = hits.map((hit, index) => ({ hit, index })).sort((a, b) => b.hit.score - a.hit.score || a.index - b.index).map((entry) => entry.hit);
    return limit === undefined ? ordered : ordered.slice(0, limit);
  };

  const queries = {
    getDeprioritizedPathMatcher: () => world.deprioritized,
    generatedPredicateFor: (paths: Iterable<string>) => {
      const flagged = new Set<string>();
      for (const path of paths) if (world.headerGenerated?.has(path)) flagged.add(path);
      return (filePath: string) => flagged.has(filePath) || /(\.pb\.go|\.pulsar\.go|(^|\/)generated\/|\.g\.dart$)/.test(filePath);
    },
    getDominantFile: world.dominantFile === undefined ? undefined : () => world.dominantFile ?? null,

    findNodesByExactName: (names: string[], options: Options = {}): SearchResult[] => {
      const wanted = new Set(names.map((name) => name.toLowerCase()));
      const hits = world.nodes
        .filter((node) => kindOk(node, options.kinds) && wanted.has(node.name.toLowerCase()))
        .map((node) => ({ node, score: quantize(40 + 30 * unit(`exact:${node.id}`) - node.name.length / 10) }));
      return ranked(hits, options.limit ?? 50);
    },

    searchNodes: (term: string, options: Options = {}): SearchResult[] => {
      // Like the real full-text index, a camelCase name is ONE token: a word only matches at the
      // start of a name, or at the start of a path segment. Infix matches are not found here.
      const needle = term.toLowerCase();
      const hits = world.nodes
        .filter((node) => kindOk(node, options.kinds) && (node.name.toLowerCase().startsWith(needle) || node.filePath.toLowerCase().split(/[^a-z0-9]+/).some((segment) => segment.startsWith(needle))))
        .map((node) => ({ node, score: quantize(3 + 50 * unit(`fts:${node.id}:${needle}`)) }));
      return ranked(hits, options.limit ?? 100);
    },

    findNodesByNameSubstring: (substring: string, options: Options & { excludePrefix?: boolean } = {}): SearchResult[] => {
      const needle = substring.toLowerCase();
      const hits = world.nodes
        .filter((node) => {
          const name = node.name.toLowerCase();
          return kindOk(node, options.kinds) && name.includes(needle) && !(options.excludePrefix && name.startsWith(needle));
        })
        .map((node) => ({ node, score: 1 + unit(`sub:${node.id}`) }));
      // The real lookup returns shortest names first.
      return hits.sort((a, b) => a.node.name.length - b.node.name.length).slice(0, options.limit ?? 30);
    },

    findEdgesBetweenNodes: (ids: string[], kinds?: EdgeKind[]): Edge[] => {
      const inside = new Set(ids);
      return world.edges.filter((edge) => inside.has(edge.source) && inside.has(edge.target) && (!kinds || kinds.includes(edge.kind))).map((edge) => ({ ...edge }));
    },
    getNodeById: (id: string): Node | null => byId.get(id) ?? null,
    getOutgoingEdges: (id: string, kinds?: EdgeKind[]): Edge[] =>
      (outgoing.get(id) ?? []).filter((edge) => !kinds || kinds.length === 0 || kinds.includes(edge.kind)).map((edge) => ({ ...edge })),
  };

  const traverser = {
    traverseBFS: (start: string, options: { maxDepth?: number; edgeKinds?: EdgeKind[]; nodeKinds?: NodeKind[]; direction?: string; limit?: number } = {}): Subgraph => {
      const nodes = new Map<string, Node>();
      const edges: Edge[] = [];
      const origin = byId.get(start);
      if (!origin) return { nodes, edges, roots: [start] };
      const limit = options.limit ?? Number.POSITIVE_INFINITY;
      const maxDepth = options.maxDepth ?? Number.POSITIVE_INFINITY;
      nodes.set(start, origin);
      let frontier = [start];
      for (let depth = 0; depth < maxDepth && frontier.length > 0; depth++) {
        const next: string[] = [];
        for (const id of frontier) {
          const around = [...(outgoing.get(id) ?? []), ...(incoming.get(id) ?? [])];
          for (const edge of around) {
            if (options.edgeKinds && !options.edgeKinds.includes(edge.kind)) continue;
            const other = edge.source === id ? edge.target : edge.source;
            const neighbor = byId.get(other);
            if (!neighbor || !kindOk(neighbor, options.nodeKinds)) continue;
            if (!nodes.has(other)) {
              if (nodes.size >= limit) continue;
              nodes.set(other, neighbor);
              next.push(other);
            }
            if (!edges.some((known) => known.source === edge.source && known.target === edge.target && known.kind === edge.kind)) edges.push({ ...edge });
          }
        }
        frontier = next;
      }
      return { nodes, edges, roots: [start] };
    },

    getTypeHierarchy: (id: string): Subgraph => {
      const nodes = new Map<string, Node>();
      const edges: Edge[] = [];
      const origin = byId.get(id);
      if (!origin) return { nodes, edges, roots: [id] };
      nodes.set(id, origin);
      const hierarchy = (edge: Edge): boolean => edge.kind === 'extends' || edge.kind === 'implements';
      let frontier = [id];
      for (let depth = 0; depth < 3 && frontier.length > 0; depth++) {
        const next: string[] = [];
        for (const current of frontier) {
          for (const edge of [...(outgoing.get(current) ?? []), ...(incoming.get(current) ?? [])].filter(hierarchy)) {
            const other = edge.source === current ? edge.target : edge.source;
            const neighbor = byId.get(other);
            if (!neighbor) continue;
            if (!nodes.has(other)) {
              nodes.set(other, neighbor);
              next.push(other);
            }
            if (!edges.some((known) => known.source === edge.source && known.target === edge.target && known.kind === edge.kind)) edges.push({ ...edge });
          }
        }
        frontier = next;
      }
      return { nodes, edges, roots: [id] };
    },
  };

  return { queries: queries as unknown as QueryBuilder, traverser: traverser as unknown as GraphTraverser };
}
